### ISSUE TITLE
sài sao vậy bạn ơi 🥲

### ISSUE THREAD

**Issue by luanon404** [hiroshil/MDM_server-fork#1]

**Comment by hiroshil** [comment]
done!
![image](https://github.com/hiroshil/MDM_server/assets/28723261/9f98a275-8d53-4c7f-87f9-f9df4a7fca01)

**Comment by luanon404** [comment]
> done! ![image](https://user-images.githubusercontent.com/28723261/266649035-9f98a275-8d53-4c7f-87f9-f9df4a7fca01.png)

ý py mấy ý chạy py3.11 nó lỗi module tùm lum
